DROP TABLE IF EXISTS product;

CREATE TABLE employee (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  NAME TEXT NOT NULL,
  SURNAME TEXT NOT NULL
);

INSERT INTO employee (NAME, SURNAME) VALUES ('MIETEK', 'MIETKOWSKI');
INSERT INTO employee (NAME, SURNAME) VALUES ('KAZEK', 'KAZOWSKI');
INSERT INTO employee (NAME, SURNAME) VALUES ('BORYS', 'BORYSEWICZ');
INSERT INTO employee (NAME, SURNAME) VALUES ('OWCZAREK', 'NIEMIECKI');